add hardhat-interface-generator package
scaffold-eth/scaffold-eth pull request #307
Opened 2021-08-04 20:43 UTC by julianmrodri

* Solves: #245 
* Adds the `hardhat-interface-generator` package that allows you to create interfaces based from a contract.
* Adds the required command so you can run `yarn gen-interface`
```bash
$ yarn gen-interface "YourContract"
```

```
yarn run v1.22.5
$ yarn workspace @scaffold-eth/hardhat gen-interface YourContract
$ hardhat gen-interface YourContract
Generated interface IYourContract
✨  Done in 1.61s.
```

2021-08-11 16:42 UTC, codenamejason requested changes
Everything looks good, I tested it on my local with no issues. Just need to rename it to "interface" and we are all good.

2021-08-11 16:42 UTC, codenamejason commented on packages/hardhat/package.json
> +    "gen-interface": "hardhat gen-interface",
rename to "interface".

2021-08-11 17:38 UTC, julianmrodri commented on package.json
> +    "gen-interface": "yarn workspace @scaffold-eth/hardhat gen-interface",
Done.

2021-08-11 17:38 UTC, julianmrodri commented on packages/hardhat/package.json
> +    "gen-interface": "hardhat gen-interface",
Done

2021-09-07 15:50 UTC, codenamejason approved these changes

2021-09-09 21:08 UTC, closed without merging

2021-09-09 21:16 UTC, StErMi commented
Yesterday @austintgriffith suggested to me this package and I was not totally sold by it. It's maybe fine to generate the interface of a "simple" contract but in my case where the contract was extending OpenZeppelin contracts, it generated a "faulty" interface that it was not usable. 

I had to delete it and write it manually by myself. I'll copy what I've said to @austintgriffith as a feedback

> I’ve tried it but it’s not good or at least not good for a complex contract like this that relies on external. it does not rely on OpenZeppelin interface and the code generated does not compile very well (a lot of warnings) because of the overloaded method, he does not add the SPDX-License and he does not add the pragma