Added vyper example contract
scaffold-eth/scaffold-eth pull request #824
Opened 2022-07-13 21:02 UTC by emilianobonassi

Solving #130

2022-07-13 21:15 UTC, bhndt requested changes
0xCa0b051804f57412600C2597d62E688d813694Ba get addreas

2022-07-27 04:47 UTC, Ataxia123 approved these changes

2022-07-27 05:27 UTC, Ataxia123 commented
does this work? I cant get vyper to create artifacts for the react-app to hold

2022-07-27 08:19 UTC, emilianobonassi commented
@Ataxia123 what error do you get?

2022-09-27 07:20 UTC, closed without merging